### ISSUE TITLE
Cannot select proposal=Standard in request for photometric standard observation

### ISSUE THREAD

**Issue by nvolgenau** [LCOGT/calibration-tom#29]
User "eng" is the PI on 2 proposals (TOM demo scheduler, Cal-TOM scheduler) and a Co-I on 11 proposals (including "standard"). User "nvolgenau" is PI on 28 proposals (including "standard") and Co-I on 13 proposals. When I draft a request to observe a photometric standard, as either user, the Proposal drop-down menu only shows 8 options, and none of them are "standard". Observations of photometric standards should be made for the "standard" proposal.

Lindy noted that "the calibration-tom connects to the observation portal with the eng API key." Why can't user "eng" submit a request for any proposal for which "eng" is a PI or Co-I?

**Comment by dmcollom** [comment]
So the TOM Toolkit gets proposals from the Observation Portal API, and it filters out just ones marked as "current", which I believe means that the proposal is not part of the semester. The options are to put the `standard` proposal in the semester, or override a certain function in `calibration-tom` to get non-current proposals as well as current ones.

**Comment by nvolgenau** [comment]
Thanks for the add'l information. The "standards" proposal is "active". However, it did not have any hours allocated for the 2021A semester, because it is a "direct submission only" proposal. (Observations can be requested without pre-allocated hours.) I allocated 2021A hours for every imager type, and now "standards" shows on the list of eligible proposals in Calibration-TOM.
