### ISSUE TITLE
TOM displays require "Seasonal start" and "Seasonal end" information

### ISSUE THREAD

**Issue by nvolgenau** [LCOGT/calibration-tom#34]
It's possible to create a target without setting values for "Seasonal start" and "Seasonal end". However, doing so triggers an error when the TOM tries to display various pages.

The "Seasonal" information should not be essential for TOM displays. If the start and end dates are not available when the target is created, then a placeholder should be inserted.

One example. Even if the new target is not an NRES calibrator, the "NRES Cadences" display will instead show an error page with: 
* Exception Value: | 'NoneType' object has no attribute 'float_value'
* Exception Location: | /Users/nvolgenau/LCOGT/cal_obs_scheduling/calibration-tom/targeted_calibrations/models.py, line 16, in target_is_in_season

Another example. If I want to edit the target's description, to add the "Seasonal" information, I get an error message with:
* Exception Value: | invalid literal for int() with base 10: ''
* Exception Location: | /Users/nvolgenau/LCOGT/cal_obs_scheduling/calibration-tom/calibrations/templatetags/calibrations_extras.py, line 23, in display_seasonal_start_or_end

So, it's not even possible to fix or delete the problem target. This is preventing me from making changes to my local Cal-TOM.

**Comment by dmcollom** [comment]
This is fixed for both cases, albeit with a caveat. The latter case has been fixed for all cases. The former is fixed for the referenced NRES Cadences view, but is done so by ensuring that the form doesn't attempt to calculate seasonality of non-NRES targets. As a result, this will still raise a stack trace if an NRES target doesn't have seasonal values, or if another view attempts to determine seasonality of non-seasonal targets. This should result in a more elegant error in the long term, but should be fine for now.

**Comment by nvolgenau** [comment]
The "NRES Cadences" display no longer triggers the exception.

For the second example: When I try to edit any target's description, I now get this error:

> There was a problem authenticating with LCO: b'{"detail":"Invalid token."}'. Please check that you have the correct credentials in the corresponding settings variable. https://tom-toolkit.readthedocs.io/en/stable/customization/customsettings.html

That url shows "This page does not exist yet." Maybe the url should be: 
https://tom-toolkit.readthedocs.io/en/stable/common/customsettings.html ? That page suggests that with AUTH_STRATEGY = READ_ONLY in settings.py "allows unauthenticated users to view most pages on your TOM, but not to change anything."

I'm logged in to the TOM. I'm a superuser. What further authentication is needed now?

**Comment by dmcollom** [comment]
Good spot on the documentation error--I've fixed that in the base TOM Toolkit, so that will propagate to `calibration-tom` at some point.

Can you specify if this is your local TOM or on dev/production?

**Comment by nvolgenau** [comment]
This is my local TOM.

**Comment by dmcollom** [comment]
So an API key is still required to do anything LCO-related, which is just a product of our LCO services requiring an API key. Your superuser status isn't really related to that. However, it's concerning that this is happening on target edit. When you say "try to edit any target's description", can you be more specific about what page you're accessing? Maybe more specifically the URL?

**Comment by dmcollom** [comment]
Also, as I can't seem to reproduce it, can you run `pip freeze | grep tomtoolkit` and tell me what the output is?

**Comment by nvolgenau** [comment]
I get the error when I create a new target. I also get the error when I click on a Target ID from my target list. I expect to get to a url like http://calibration-tom.lco.gtn/targets/39/

**Comment by nvolgenau** [comment]
(tom_env) minna:calibration-tom nvolgenau$ pip freeze | grep tomtoolkit
tomtoolkit==2.6.3

**Comment by dmcollom** [comment]
Can you run a `pip install --upgrade tomtoolkit`, ensure that you're on `2.6.8`, and try again?

**Comment by nvolgenau** [comment]
Upgraded to 2.6.8. The error is the same.

**Comment by dmcollom** [comment]
Alright, I have to say that I'm a little stumped. Have you made any code changes to it yet? Is there some modification you have on the target detail page that might interact with LCO?

**Comment by nvolgenau** [comment]
I haven't made any code changes, just added targets through the UI. The error blocks me from getting to a target detail page. That's why I wondered whether it was a login/permissions problem. My setting for unauthenticated users is READ_ONLY.

**Comment by nvolgenau** [comment]
Rachel figured it out. I needed to do two things: 1. set the API KEY in the virtual environment before activating, and 2. make the API KEY environment variable name consistent with settings.py.

An additional task will be to make sure these steps are documented in the README.
