### ISSUE TITLE
"View ConfigDB Instruments" button triggers "AttributeError at /nres/instruments"

### ISSUE THREAD

**Issue by nvolgenau** [LCOGT/calibration-tom#40]
There's a button labeled "View ConfigDB Instruments" at the bottom of the NRES tab (http://calibration-tom.lco.gtn/nres/nres). Clicking it should display the contents of instrument_type_list.html filled with information about the NRES units. Instead, clicking the button yields an "AttributeError at /nres/instruments". A screenshot of the error summary is attached.

![AttributeError 20210907](https://user-images.githubusercontent.com/9870293/132400310-e66e8607-8e47-4df5-81e4-e4a806a45187.png)

Line 116 of configdb_connections.py is:

`instrument_type: str = '',`

**Comment by dmcollom** [comment]
This is fixed in both dev and prod--just tested.
